### ISSUE TITLE
Support Int64 arguments in Filters

### ISSUE THREAD

**Issue by Jonny007-MKD** [beto-rodriguez/SuperXml#3]
Hi,

In my XML I need to use very large integers. I noticed that you parse a number first as Int32 and then as Single. Because single looses precision that I would like to keep it would be nice if you could try to parse a number as Int64 first.

greetz
Jonny007

**Comment by beto-rodriguez** [comment]
Hi, Can you please show an example, this library uses dynamic types. I am not sure abour the single-int32 issue

**Comment by Jonny007-MKD** [comment]
Hi,

well I am using a filter that converts seconds to nanoseconds, nothing fancy: `{{10 | s_to_ns}}`
The filter gets an object passed, which is in this case a {System.Int32} with value `10`. The result shall be: `10000000000` (simply 9 `0`s added or value multiplied by 1E+9)

When the number gets bigger and the Int32 is not large enough `{{12345678901 | s_to_ns}}`, a float {System.Single} is passed as argument with value `1.23456788E+10`. Here you can see that a float is not precise enough to carry all digits.

When the number gets even bigger (E+19 or more), the filter is not even called but simply ignored, the compiled result is the filter definition: `{{12345678901234567890 | s_to_ns}}`. This is extra strange because a float can contain values up to E+38.

I don't know about dynamic types but it would be nice if you would refine the mechanism of what argument is passed, like following a list of possible types and using the next one if the parsing is somehow incorrect:
- `int`
- `long`
- `float`
- `double`
- `string`    as fallback, to filter enums, translate or do other stuff

**Comment by beto-rodriguez** [comment]
Ok. In this case `{{10 | s_to_ns}}`, wich means  `{{expression | filter}}`. the compiler works this way, all it knows is that you are passing an expression `10` in this case, he does not know if it is a logical expression (`10 > 5`), math operation (`10 * 50`), maybe just a simple type (`string`, `int`, `double`), maybe a `class`, [this is the function](https://github.com/beto-rodriguez/SuperXml/blob/master/SuperXML/Compiler.cs#L561) that evaluates the expression, your expression is beeing evaluated by `NCalc` (the only dependecy package of this libary) in [this line ](https://github.com/beto-rodriguez/SuperXml/blob/master/SuperXML/Compiler.cs#L591), `NCalc` parses `10` as `int32` but `12345678901` as `float`, Im not sure about how does NCalc decides if parse it as `int`, `double`, or `float`, but instead you can set a "strongly typed" expression as you need in your case. You need to set the type using C# instead of a string expression that will try to parse it according to `NCalc`. for example: 

``` c#
int anInteger = 10;
float aFloat = 100;
double aDouble = 10000;

var compiler = new Compiler()
                .AddKey("i", anInteger);
                .AddKey("f", aFloat);
                .AddKey("d", aDouble);
```

This is the cool thing about dynamic types, they will be evaluated in runtime, as you can see you are passing an `int`, `float` or `double` depending on the presicion you need and they will run as the type you choose. now instead of `{{10 | s_to_ns}}`, use a parameter wich you know is `double` (or `int`, or `float`, or whatever) `{{d | s_to_ns}}`, or `{{f | s_to_ns}}`(if you need `float` precision). It now will hit [this line](https://github.com/beto-rodriguez/SuperXml/blob/master/SuperXML/Compiler.cs#L573) and let `NCalc` know the type. This should run much faster too since it already knows what the expression is. Please let me know if I am clear enough and if it works.
Thanks, hope it helps you.

**Comment by Jonny007-MKD** [comment]
Hey,

I really appreciate dynamic types and this suggestion, but I want these values to be configurable in the template. Otherwise I would not have to call a filter because I could assign an "1s_in_ns" key.

As you cannot alter NCalc: In my opinion it would be nice to be able to get the string, anyway. So one could call a "translate" filter, which translates the given string into a language specified at run-time: `{{test || translate}} = "Test", {{hello || translate}} = "Hallo"`. It would also make your "currency" filter less dirty ([here](https://github.com/beto-rodriguez/SuperXml/blob/master/SuperXML/Compiler.cs#L57)) and let me parse the number on my own ;)

**Comment by beto-rodriguez** [comment]
If you need to translate this should work `{{'a string variable' | translate}}`, this forces a string, then you can parse it for your own if required.

**Comment by Jonny007-MKD** [comment]
Oh right, I haven't read this in the documentation. This is great! :) 
I noticed that NCalc parses `1.5` as Double, so it is even more weird that large numbers are parsed as Single.

Thanks!

Am 2. November 2015 14:45:20 MEZ, schrieb Alberto Rodriguez notifications@github.com:
